INSERT  OR REPLACE INTO GameOptions (Type, Description, Help, "Default", "SupportsSinglePlayer")
SELECT  'GAMEOPTION_JUNGLE_PLAINS', 'TXT_KEY_GAME_OPTION_JUNGLE_PLAINS', 'TXT_KEY_GAME_OPTION_JUNGLE_PLAINS_HELP', 1,1 UNION ALL
SELECT  'GAMEOPTION_ARCTIC_RIVER', 'TXT_KEY_GAME_OPTION_ARCTIC_RIVER', 'TXT_KEY_GAME_OPTION_ARCTIC_RIVER_HELP', 1,1 UNION ALL
SELECT  'GAMEOPTION_FLOOD_DESERT', 'TXT_KEY_GAME_OPTION_FLOOD_DESERT', 'TXT_KEY_GAME_OPTION_FLOOD_DESERT_HELP', 1,1;

INSERT  OR REPLACE INTO Language_en_US (Tag, Text)
SELECT  'TXT_KEY_GAME_OPTION_JUNGLE_PLAINS', 'Jungle on Plains' UNION ALL
SELECT  'TXT_KEY_GAME_OPTION_JUNGLE_PLAINS_HELP', 'Jungle always appears on Plains.' UNION ALL
SELECT  'TXT_KEY_GAME_OPTION_ARCTIC_RIVER', 'Warmer Arctic River' UNION ALL
SELECT  'TXT_KEY_GAME_OPTION_ARCTIC_RIVER_HELP', 'Tundra river will turned into Plains river, and Snow river will turned into Tundra river.' UNION ALL
SELECT  'TXT_KEY_GAME_OPTION_FLOOD_DESERT', 'Desert Flood Plains' UNION ALL
SELECT  'TXT_KEY_GAME_OPTION_FLOOD_DESERT_HELP', 'Forcing Desert river to always have Flood Plains.';
